import {
  pgTable,
  uuid,
  text,
  timestamp,
  check,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { alertTypeEnum, alertStatusEnum, severityEnum } from "./enums";
import { assets } from "./assets";
import { cves } from "./cves";
import { assetVulnerabilities } from "./asset-vulnerabilities";
import { scanImports } from "./scan-imports";
import { remediationTasks } from "./remediation-tasks";
import { profiles } from "./profiles";

/**
 * Alerts
 *
 * Security alerts generated by the system (Inngest jobs) or manually.
 *
 * DESIGN: Uses multiple nullable FK columns for polymorphic entity references
 * instead of a generic entity_type/entity_id pattern. Rationale:
 *   - PostgreSQL enforces FK integrity on each column individually
 *   - Drizzle has better type support for explicit FKs
 *   - Queries are cleaner (WHERE related_asset_id = ? vs entity_type + entity_id)
 *   - Most alerts relate to 1-3 entities simultaneously
 *
 * CHECK constraint ensures at least one related entity is set.
 *
 * Status-based lifecycle: never hard-delete. Resolved/dismissed alerts
 * remain for audit trail.
 */
export const alerts = pgTable(
  "alerts",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    title: text("title").notNull(),
    description: text("description"),

    type: alertTypeEnum("type").notNull(),
    severity: severityEnum("severity").notNull(),
    status: alertStatusEnum("status").notNull().default("new"),

    // ─── Polymorphic entity references (all nullable) ─────────────────
    // At least one must be non-null (enforced by CHECK constraint below).

    /** FK → assets.id. onDelete: set null — alert survives asset removal. */
    relatedAssetId: uuid("related_asset_id").references(() => assets.id, {
      onDelete: "set null",
    }),

    /** FK → cves.id. onDelete: set null. */
    relatedCveId: uuid("related_cve_id").references(() => cves.id, {
      onDelete: "set null",
    }),

    /** FK → asset_vulnerabilities.id. onDelete: set null. */
    relatedAssetVulnerabilityId: uuid(
      "related_asset_vulnerability_id"
    ).references(() => assetVulnerabilities.id, { onDelete: "set null" }),

    /** FK → scan_imports.id. onDelete: set null. */
    relatedScanImportId: uuid("related_scan_import_id").references(
      () => scanImports.id,
      { onDelete: "set null" }
    ),

    /** FK → remediation_tasks.id. onDelete: set null. */
    relatedRemediationTaskId: uuid("related_remediation_task_id").references(
      () => remediationTasks.id,
      { onDelete: "set null" }
    ),

    // ─── Ownership & resolution ───────────────────────────────────────

    /** FK → profiles.id — alert owner/assignee. onDelete: set null. */
    ownerId: uuid("owner_id").references(() => profiles.id, {
      onDelete: "set null",
    }),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),

    /** FK → profiles.id — who resolved the alert. onDelete: set null. */
    resolvedBy: uuid("resolved_by").references(() => profiles.id, {
      onDelete: "set null",
    }),
  },
  (table) => [
    /**
     * CHECK: At least one related entity must be set.
     * An alert with zero entity references is meaningless and likely a bug.
     */
    check(
      "chk_alert_has_relation",
      sql`${table.relatedAssetId} IS NOT NULL
        OR ${table.relatedCveId} IS NOT NULL
        OR ${table.relatedAssetVulnerabilityId} IS NOT NULL
        OR ${table.relatedScanImportId} IS NOT NULL
        OR ${table.relatedRemediationTaskId} IS NOT NULL`
    ),

    // ─── Operational indexes ──────────────────────────────────────────
    index("idx_alerts_status").on(table.status),
    index("idx_alerts_severity").on(table.severity),
    index("idx_alerts_created").on(table.createdAt),
    index("idx_alerts_owner").on(table.ownerId),
    // Relation indexes — used when viewing alerts from entity detail pages
    index("idx_alerts_asset").on(table.relatedAssetId),
    index("idx_alerts_cve").on(table.relatedCveId),
    index("idx_alerts_av").on(table.relatedAssetVulnerabilityId),
    index("idx_alerts_scan").on(table.relatedScanImportId),
    index("idx_alerts_task").on(table.relatedRemediationTaskId),
  ]
);
